example_list_1:
  description: Description for example reference list 1
  resource_name: projects/sierpinski-secops/locations/eu/instances/67ebaddb-d421-47c2-97fd-a20adeec48a8/referenceLists/example_list_1
  revision_create_time: '2024-09-30T16:44:42.692111Z'
  rule_associations_count: null
  rules: null
  syntax_type: REFERENCE_LIST_SYNTAX_TYPE_PLAIN_TEXT_STRING
