firewall_rules_modified_or_deleted:
  alerting: true
  enabled: true
gcp_admin_privileged_roles_added_to_service_accounts:
  alerting: true
  enabled: true
gcp_multiple_service_apis_disabled:
  alerting: true
  enabled: true
permissions_granted_over_SA:
  alerting: true
  enabled: true
